eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8765/eureka/
  instance:
    hostname: localhost
message: Hello from config files
microservice:
    db-service:
        endpoints:
            endpoint:
                uri: http://db-service/get
            create:
                uri: http://db-service/create
            get:
                uri: http://db-service/getbyid/
            update:
                uri: http://db-service/update
            delete:
                uri: http://db-service/delete/
