eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
    db-service:
        endpoints:
            endpoint:
                uri: http://db-service/get
